url: "https://hagg3.github.io"
baseurl: "/edenarchive"
theme: minima

title: Eden Worlds Archive

exclude:
  - z_Uploading
  - node-mapgen-broken
  - admin
  - admin-filelist
  - z_scripts
  - node-mapgen
  - z_AutoDownloader
  - "*.py"
  - Gemfile
  - Gemfile.lock

header_pages:
#  - articles.md
  - blog.md
  - links.md
  - worlds.md


collections:
  worlds:
    output: true
    permalink: /worlds/:name/
  articles:
    output: true
    permalink: /articles/:name/

